import { StyleSheet } from 'react-native';
import type { Theme } from '../../styles/theme';

export const createStyles = (theme: Theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background.primary,
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.background.primary,
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: theme.text.secondary,
  },
  section: {
    backgroundColor: theme.glass.subtle,
    marginHorizontal: 15,
    marginTop: 15,
    padding: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.border.subtle,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: theme.border.subtle,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: theme.text.primary,
    marginLeft: 10,
  },
  infoRow: {
    marginBottom: 12,
  },
  label: {
    fontSize: 14,
    color: theme.text.secondary,
    marginBottom: 4,
  },
  value: {
    fontSize: 16,
    color: theme.text.primary,
    fontWeight: '600',
  },
  codeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  invitationCode: {
    fontSize: 18,
    color: theme.accent.blue,
    fontWeight: '700',
    letterSpacing: 2,
  },
  copyButton: {
    padding: 8,
    backgroundColor: theme.accent.blueSubtle,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.accent.blueDim,
  },
  helperText: {
    fontSize: 12,
    color: theme.text.tertiary,
    marginTop: 10,
    fontStyle: 'italic',
  },
  emptyText: {
    fontSize: 14,
    color: theme.text.secondary,
    fontStyle: 'italic',
  },
  memberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
  },
  memberRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: theme.border.medium,
  },
  memberIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.accent.blueSubtle,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: theme.accent.blueDim,
  },
  memberInfo: {
    flex: 1,
  },
  memberNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 2,
  },
  memberAvatar: {
    fontSize: 24,
  },
  memberEmail: {
    fontSize: 16,
    color: theme.text.primary,
    fontWeight: '600',
  },
  memberEmailSmall: {
    fontSize: 12,
    color: theme.text.secondary,
    marginBottom: 4,
  },
  memberRole: {
    fontSize: 12,
    color: theme.accent.blue,
    backgroundColor: theme.accent.blueSubtle,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    fontWeight: '600',
  },
  memberName: {
    fontSize: 14,
    color: theme.text.secondary,
    marginBottom: 4,
  },
  creatorBadge: {
    fontSize: 12,
    color: theme.accent.orange,
    fontWeight: '600',
  },
  youBadge: {
    fontSize: 12,
    color: theme.accent.green,
    fontWeight: '600',
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 15,
    backgroundColor: 'rgba(255, 59, 48, 0.8)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: theme.accent.redDim,
    shadowColor: '#FF3B30',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 5,
  },
  logoutButtonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '600',
    marginLeft: 10,
  },
  footer: {
    alignItems: 'center',
    paddingVertical: 30,
    paddingBottom: 40,
  },
  footerText: {
    fontSize: 12,
    color: theme.text.tertiary,
    marginBottom: 4,
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  editButton: {
    padding: 8,
    backgroundColor: theme.accent.blueSubtle,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.accent.blueDim,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: theme.overlay.dark,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: theme.background.secondary,
    borderRadius: 24,
    padding: 24,
    width: '85%',
    maxWidth: 400,
    borderWidth: 1,
    borderColor: theme.border.subtle,
    shadowColor: theme.accent.blue,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.3,
    shadowRadius: 24,
    elevation: 10,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 20,
    color: theme.text.primary,
  },
  modalInput: {
    backgroundColor: theme.glass.subtle,
    borderWidth: 1.5,
    borderColor: theme.border.medium,
    borderRadius: 14,
    padding: 16,
    marginBottom: 20,
    fontSize: 16,
    color: theme.text.primary,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  modalButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 14,
    minWidth: 90,
    alignItems: 'center',
    borderWidth: 1,
    marginLeft: 12,
  },
  modalButtonCancel: {
    backgroundColor: theme.glass.subtle,
    borderColor: theme.border.medium,
    marginLeft: 0,
  },
  modalButtonConfirm: {
    backgroundColor: theme.accent.blueLight,
    borderColor: theme.accent.blueDim,
    shadowColor: theme.accent.blue,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 5,
  },
  modalButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  modalButtonTextCancel: {
    color: theme.text.primary,
    fontSize: 16,
    fontWeight: '600',
  },
  roleDisplay: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  avatar: {
    fontSize: 24,
  },
  roleList: {
    maxHeight: 350,
    marginBottom: 20,
  },
  roleItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    borderRadius: 12,
    marginBottom: 10,
    backgroundColor: theme.glass.subtle,
    borderWidth: 1,
    borderColor: theme.border.subtle,
  },
  roleItemSelected: {
    backgroundColor: theme.accent.blueSubtle,
    borderColor: theme.accent.blueDim,
  },
  roleAvatar: {
    fontSize: 28,
    marginRight: 12,
  },
  roleText: {
    fontSize: 16,
    color: theme.text.primary,
    fontWeight: '500',
    flex: 1,
  },
  roleTextSelected: {
    color: theme.accent.blue,
    fontWeight: '600',
  },
  settingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  settingInfo: {
    flex: 1,
    marginRight: 12,
  },
  settingLabel: {
    fontSize: 16,
    color: theme.text.primary,
    fontWeight: '600',
    marginBottom: 4,
  },
  settingDescription: {
    fontSize: 13,
    color: theme.text.secondary,
    lineHeight: 18,
  },
  themeSegmentedRow: {
    flexDirection: 'row',
    gap: 6,
  },
  themeButton: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 4,
    borderRadius: 10,
    alignItems: 'center',
    backgroundColor: theme.glass.subtle,
    borderWidth: 1,
    borderColor: theme.border.medium,
  },
  themeButtonActive: {
    backgroundColor: theme.accent.blueSubtle,
    borderColor: theme.accent.blueDim,
  },
  themeButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.text.secondary,
  },
  themeButtonTextActive: {
    color: theme.accent.blue,
  },
    dangerTitle: {
    color: '#FF3B30',
  },
  dangerWarning: {
    fontSize: 14,
    color: '#FF6B6B',
    marginBottom: 15,
    lineHeight: 20,
  },
  deleteAccountButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 15,
    backgroundColor: 'rgba(139, 0, 0, 0.9)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 0, 0, 0.5)',
    shadowColor: '#8B0000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 5,
  },
  deleteAccountButtonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
    marginLeft: 10,
  },
  requestsBadge: {
    marginLeft: 10,
    backgroundColor: '#FFB340',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 6,
  },
  requestsBadgeText: {
    color: '#000',
    fontSize: 12,
    fontWeight: '700',
  },
  requestActions: {
    flexDirection: 'row',
    gap: 8,
  },
  requestActionButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  requestApproveButton: {
    backgroundColor: 'rgba(48, 209, 88, 0.8)',
  },
  requestRejectButton: {
    backgroundColor: 'rgba(255, 69, 58, 0.7)',
  },
  legalButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: theme.border.medium,
  },
  legalButtonText: {
    flex: 1,
    fontSize: 16,
    color: theme.text.primary,
    marginLeft: 12,
    fontWeight: '500',
  },
});
