import { StyleSheet } from 'react-native';
import { COLORS, RADIUS, SPACING } from '../../styles/theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background.primary,
  },
  listCard: {
    backgroundColor: COLORS.glass.subtle,
    margin: 10,
    padding: 18,
    borderRadius: RADIUS.xlarge,
    borderWidth: 1,
    borderColor: COLORS.border.subtle,
    position: 'relative',
  },
  completedCard: {
    backgroundColor: 'rgba(48, 209, 88, 0.1)',
    borderColor: 'rgba(48, 209, 88, 0.3)',
  },
  syncIndicator: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 10,
    height: 10,
    borderRadius: 5,
    zIndex: 1,
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  listTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 10,
  },
  listName: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.text.primary,
  },
  completedText: {
    color: COLORS.text.secondary,
  },
  completedBadge: {
    fontSize: 12,
    color: COLORS.accent.green,
    backgroundColor: COLORS.accent.greenDim,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: SPACING.sm,
    fontWeight: '600',
  },
  listDate: {
    fontSize: 14,
    color: COLORS.text.secondary,
  },
  listDateFormatted: {
    fontSize: 15,
    color: COLORS.text.primary,
    fontWeight: '600',
    marginTop: 4,
  },
  storeName: {
    fontSize: 17,
    color: COLORS.text.primary,
    fontWeight: '700',
    marginTop: 6,
  },
  listDateSecondary: {
    fontSize: 13,
    color: COLORS.text.tertiary,
    marginTop: 4,
  },
  listBadges: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  shoppingBadge: {
    fontSize: 12,
    color: COLORS.accent.orange,
    backgroundColor: 'rgba(255, 179, 64, 0.2)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    fontWeight: '600',
  },
  deleteIconButton: {
    padding: 4,
  },
  deleteIcon: {
    fontSize: 18,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 100,
  },
  emptyText: {
    fontSize: 22,
    color: COLORS.text.primary,
    marginBottom: 10,
    fontWeight: '600',
  },
  emptySubtext: {
    fontSize: 16,
    color: COLORS.text.secondary,
  },
  scanButton: {
    position: 'absolute',
    right: 20,
    bottom: 100,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    backgroundColor: 'rgba(52, 199, 89, 0.8)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(52, 199, 89, 0.4)',
    shadowColor: COLORS.accent.green,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 16,
    elevation: 10,
  },
  scanButtonDisabled: {
    backgroundColor: 'rgba(142, 142, 147, 0.5)',
    borderColor: 'rgba(142, 142, 147, 0.3)',
    shadowColor: '#8E8E93',
  },
  scanButtonIcon: {
    fontSize: 20,
    marginRight: 8,
  },
  scanButtonText: {
    color: COLORS.text.primary,
    fontSize: 16,
    fontWeight: '600',
  },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.accent.blue,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 12,
    overflow: 'hidden',
  },
  fabGradient: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fabText: {
    fontSize: 36,
    color: COLORS.text.primary,
    fontWeight: '300',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: COLORS.overlay.dark,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    borderRadius: RADIUS.modal,
    padding: SPACING.xxl,
    width: '85%',
    maxWidth: 400,
    borderWidth: 1,
    borderColor: COLORS.border.medium,
    shadowColor: COLORS.accent.blue,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.3,
    shadowRadius: 24,
    elevation: 10,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 10,
    color: COLORS.text.primary,
  },
  modalSubtitle: {
    fontSize: 16,
    color: COLORS.text.secondary,
    marginBottom: 15,
  },
  dateButton: {
    backgroundColor: COLORS.glass.medium,
    borderWidth: 1,
    borderColor: COLORS.border.medium,
    borderRadius: RADIUS.xlarge,
    padding: 16,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dateButtonText: {
    fontSize: 18,
    color: COLORS.text.primary,
    fontWeight: '600',
  },
  calendarIcon: {
    fontSize: 24,
  },
  datePreview: {
    fontSize: 12,
    color: COLORS.text.tertiary,
    marginBottom: 20,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  modalButton: {
    paddingVertical: 12,
    paddingHorizontal: SPACING.xxl,
    borderRadius: RADIUS.large,
    minWidth: 90,
    alignItems: 'center',
    borderWidth: 1,
    marginLeft: 12,
  },
  modalButtonCancel: {
    backgroundColor: COLORS.glass.medium,
    borderColor: COLORS.border.medium,
    marginLeft: 0,
  },
  modalButtonConfirm: {
    borderWidth: 0,
    overflow: 'hidden',
    padding: 0,
  },
  modalButtonConfirmGradient: {
    paddingVertical: 12,
    paddingHorizontal: SPACING.xxl,
    borderRadius: RADIUS.large,
    minWidth: 90,
    alignItems: 'center',
  },
  modalButtonText: {
    color: COLORS.text.primary,
    fontSize: 16,
    fontWeight: '600',
  },
  modalButtonTextCancel: {
    color: COLORS.text.primary,
    fontSize: 16,
    fontWeight: '600',
  },
  iosPickerContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: COLORS.overlay.dark,
  },
  iosPickerContent: {
    backgroundColor: COLORS.background.secondary,
    borderTopLeftRadius: RADIUS.xxlarge,
    borderTopRightRadius: RADIUS.xxlarge,
    padding: SPACING.xl,
  },
  iosPickerDone: {
    overflow: 'hidden',
    borderRadius: RADIUS.medium,
    marginTop: 10,
  },
  iosPickerDoneGradient: {
    padding: 15,
    borderRadius: RADIUS.medium,
    alignItems: 'center',
  },
  iosPickerDoneText: {
    color: COLORS.text.primary,
    fontSize: 16,
    fontWeight: '600',
  },
});

export default styles;
