import { StyleSheet } from 'react-native';
import { Theme, RADIUS } from '../../styles/theme';

export const createStyles = (theme: Theme) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.background.primary,
  },
  titleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 10,
    backgroundColor: theme.glass.medium,
    borderBottomWidth: 1,
    borderBottomColor: theme.border.medium,
    gap: 10,
  },
  backButton: {
    padding: 4,
  },
  title: {
    fontSize: 20,
    fontWeight: '700',
    color: theme.text.primary,
    flex: 1,
  },
  editIcon: {
    fontSize: 20,
    padding: 5,
  },
  titleInput: {
    flex: 1,
    fontSize: 24,
    fontWeight: '700',
    color: theme.text.primary,
    backgroundColor: theme.glass.medium,
    padding: 10,
    borderRadius: RADIUS.small,
    borderWidth: 1,
    borderColor: theme.border.medium,
  },
  titleSaveButton: {
    backgroundColor: theme.accent.green,
    padding: 10,
    borderRadius: RADIUS.small,
    borderWidth: 1,
    borderColor: theme.accent.greenDim,
  },
  titleSaveButtonText: {
    fontSize: 20,
  },
  titleCancelButton: {
    backgroundColor: theme.accent.redSubtle,
    padding: 10,
    borderRadius: RADIUS.small,
    borderWidth: 1,
    borderColor: theme.accent.redDim,
  },
  titleCancelButtonText: {
    fontSize: 20,
  },
  addItemContainer: {
    flexDirection: 'row',
    padding: 10,
    backgroundColor: theme.glass.medium,
    borderBottomWidth: 1,
    borderBottomColor: theme.border.subtle,
  },
  input: {
    flex: 1,
    backgroundColor: theme.glass.subtle,
    padding: 12,
    borderRadius: RADIUS.large,
    marginRight: 10,
    borderWidth: 1,
    borderColor: theme.border.medium,
    color: theme.text.primary,
  },
  addButton: {
    backgroundColor: theme.accent.blueLight,
    padding: 10,
    borderRadius: RADIUS.medium,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.accent.blueDim,
  },
  addButtonText: {
    color: theme.text.primary,
    fontWeight: '600',
  },
  frequentItemsButton: {
    backgroundColor: theme.glass.medium,
    padding: 10,
    borderRadius: RADIUS.medium,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.border.medium,
    marginRight: 10,
    minWidth: 44,
  },
  frequentItemsIcon: {
    fontSize: 20,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.background.secondary,
    padding: 15,
    marginHorizontal: 10,
    marginBottom: 8,
    borderRadius: RADIUS.xlarge,
    borderWidth: 1,
    borderColor: theme.border.strong,
  },
  itemRowChecked: {
    backgroundColor: theme.glass.subtle,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: theme.accent.blue,
    borderRadius: 4,
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.accent.blueSubtle,
  },
  checkboxDisabled: {
    borderColor: theme.text.tertiary,
    backgroundColor: theme.glass.subtle,
    opacity: 0.5,
  },
  checkboxTextDisabled: {
    color: theme.text.tertiary,
  },
  checkboxTextChecked: {
    color: theme.accent.green,
    fontWeight: 'bold',
  },
  itemContent: {
    flex: 1,
  },
  itemContentTouchable: {
    flex: 1,
  },
  itemContentColumn: {
    flex: 1,
  },
  itemContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  suggestionRow: {
    marginTop: 4,
  },
  suggestionText: {
    fontSize: 12,
    color: theme.accent.green,
    fontStyle: 'italic',
  },
  itemNameText: {
    flex: 1,
    fontSize: 16,
    color: theme.text.primary,
    fontWeight: '600',
  },
  itemNameChecked: {
    textDecorationLine: 'line-through',
    color: theme.text.tertiary,
  },
  itemPriceText: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.text.secondary,
    minWidth: 60,
    textAlign: 'right',
  },
  itemPricePredicted: {
    color: theme.text.secondary,
    fontWeight: '400',
  },
  itemPriceChecked: {
    color: theme.text.tertiary,
  },
  itemPriceCompact: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.accent.green,
    marginLeft: 8,
  },
  itemTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  itemName: {
    fontSize: 16,
    color: theme.text.primary,
    flex: 1,
  },
  itemPrice: {
    fontSize: 16,
    fontWeight: '600',
    color: theme.accent.green,
    marginLeft: 8,
  },
  itemChecked: {
    textDecorationLine: 'line-through',
    color: theme.text.tertiary,
  },
  priceText: {
    fontSize: 14,
    color: theme.accent.green,
    marginTop: 4,
  },
  priceInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  priceInputField: {
    flex: 1,
    backgroundColor: theme.glass.subtle,
    padding: 8,
    borderRadius: RADIUS.small,
    borderWidth: 1,
    borderColor: theme.border.medium,
    color: theme.text.primary,
    fontSize: 14,
    marginRight: 8,
  },
  saveButton: {
    backgroundColor: theme.accent.green,
    padding: 8,
    borderRadius: RADIUS.small,
    borderWidth: 1,
    borderColor: theme.accent.greenDim,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 36,
  },
  saveButtonText: {
    fontSize: 16,
  },
  deleteButton: {
    fontSize: 20,
    padding: 5,
  },
  emptyState: {
    alignItems: 'center',
    padding: 40,
  },
  emptyText: {
    fontSize: 16,
    color: theme.text.secondary,
  },
  categoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingTop: 24,
    paddingBottom: 8,
  },
  categoryIcon: {
    fontSize: 16,
  },
  categoryName: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.text.tertiary,
    textTransform: 'uppercase',
    letterSpacing: 1.5,
  },
  categoryArrows: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 'auto',
  },
  arrowButton: {
    padding: 4,
  },
  saveLayoutButton: {
    backgroundColor: theme.accent.blueSubtle,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: RADIUS.small,
    borderWidth: 1,
    borderColor: theme.accent.blueDim,
  },
  saveLayoutButtonDisabled: {
    opacity: 0.5,
  },
  saveLayoutText: {
    fontSize: 14,
    color: theme.accent.blue,
    fontWeight: '600',
  },
  listScrollContainer: {
    flex: 1,
  },
  flatListContent: {
    paddingBottom: 100,
  },
  listFooter: {
    paddingHorizontal: 10,
    paddingTop: 20,
    paddingBottom: 20,
  },
  viewReceiptButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.accent.blueLight,
    padding: 16,
    borderRadius: RADIUS.xlarge,
    borderWidth: 1,
    borderColor: theme.accent.blueDim,
    gap: 10,
    marginBottom: 10,
  },
  viewReceiptIcon: {
    fontSize: 20,
  },
  viewReceiptText: {
    color: theme.text.primary,
    fontSize: 16,
    fontWeight: '600',
  },
  attachPhotoButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.glass.subtle,
    padding: 16,
    borderRadius: RADIUS.xlarge,
    borderWidth: 1,
    borderColor: theme.border.medium,
    gap: 10,
  },
  attachPhotoButtonDisabled: {
    opacity: 0.5,
  },
  attachPhotoIcon: {
    fontSize: 20,
  },
  attachPhotoText: {
    color: theme.text.primary,
    fontSize: 16,
    fontWeight: '600',
  },
  importButton: {
    backgroundColor: theme.accent.blueLight,
    padding: 12,
    borderRadius: RADIUS.medium,
    alignItems: 'center',
    marginHorizontal: 20,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: theme.accent.blueDim,
  },
  importButtonText: {
    color: theme.text.primary,
    fontSize: 14,
    fontWeight: '600',
  },
  completeButton: {
    borderRadius: RADIUS.xlarge,
    alignItems: 'center',
    overflow: 'hidden',
  },
  completeButtonGradient: {
    width: '100%',
    padding: 16,
    borderRadius: RADIUS.xlarge,
    alignItems: 'center',
  },
  completeButtonText: {
    color: theme.text.primary,
    fontSize: 16,
    fontWeight: '600',
  },
  smartStatusBar: {
    borderBottomWidth: 1,
    minHeight: 40,
  },
  statusShopping: {
    backgroundColor: 'rgba(52, 199, 89, 0.95)',
    borderBottomColor: 'rgba(52, 199, 89, 0.3)',
  },
  statusLocked: {
    backgroundColor: 'rgba(255, 149, 0, 0.9)',
    borderBottomColor: 'rgba(255, 149, 0, 0.3)',
  },
  statusCompleted: {
    backgroundColor: 'rgba(142, 142, 147, 0.9)',
    borderBottomColor: 'rgba(142, 142, 147, 0.3)',
  },
  statusContentCompact: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  statusLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  statusRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statusIcon: {
    fontSize: 16,
  },
  statusTextCompact: {
    color: theme.text.primary,
    fontSize: 14,
    fontWeight: '600',
  },
  budgetBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginLeft: 4,
  },
  budgetBadgeWarning: {
    backgroundColor: 'rgba(255, 204, 0, 0.9)',
  },
  budgetBadgeOver: {
    backgroundColor: 'rgba(255, 59, 48, 0.9)',
  },
  budgetBadgeText: {
    color: theme.text.primary,
    fontSize: 11,
    fontWeight: 'bold',
  },
  expandButton: {
    padding: 4,
  },
  expandIcon: {
    color: theme.text.primary,
    fontSize: 12,
    fontWeight: 'bold',
  },
  doneButtonCompact: {
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 16,
  },
  doneButtonText: {
    color: theme.text.primary,
    fontSize: 14,
    fontWeight: '600',
  },
  statusContentExpanded: {
    padding: 16,
  },
  expandedHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  expandedTitle: {
    color: theme.text.primary,
    fontSize: 16,
    fontWeight: 'bold',
  },
  collapseButton: {
    padding: 4,
  },
  expandedStats: {
    gap: 8,
    marginBottom: 12,
  },
  expandedRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  expandedLabel: {
    color: theme.text.secondary,
    fontSize: 13,
    fontWeight: '500',
  },
  expandedValue: {
    color: theme.text.primary,
    fontSize: 14,
    fontWeight: '600',
  },
  textOk: {
    color: theme.text.primary,
  },
  textWarning: {
    color: theme.accent.yellow,
  },
  textOver: {
    color: theme.accent.red,
  },
  expandedButtons: {
    flexDirection: 'row',
    gap: 10,
  },
  cancelButtonExpanded: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    padding: 12,
    borderRadius: RADIUS.small,
    alignItems: 'center',
  },
  cancelButtonText: {
    color: 'rgba(255, 255, 255, 0.9)',
    fontSize: 14,
    fontWeight: '500',
  },
  doneButtonExpanded: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    padding: 12,
    borderRadius: RADIUS.small,
    alignItems: 'center',
  },
  storeWarningBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.accent.yellowDim,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: theme.accent.yellowDim,
  },
  storeWarningText: {
    flex: 1,
    fontSize: 13,
    color: theme.accent.yellow,
  },
  storeWarningLink: {
    fontSize: 13,
    color: theme.accent.blue,
    fontWeight: '600',
    textDecorationLine: 'underline',
    marginLeft: 8,
  },
  changeStoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: theme.border.subtle,
  },
  changeStoreLabel: {
    flex: 1,
    fontSize: 13,
    color: theme.text.secondary,
  },
  changeStoreLink: {
    fontSize: 13,
    color: theme.accent.blue,
    fontWeight: '600',
    textDecorationLine: 'underline',
    marginLeft: 8,
  },
  loadingOverlay: {
    position: 'absolute',
    left: 0,
    top: 0,
    right: 0,
    bottom: 0,
    backgroundColor: theme.overlay.dark,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 999,
  },
  gradientDoneButton: {
    borderRadius: 8,
    alignItems: 'center' as const,
    padding: 12,
    width: '100%' as const,
  },
});

export default createStyles;
